FROM tomcat:9.0-jdk11-openjdk-slim
RUN apt-get update && apt-get install -y libnss3 git
COPY . ./app
RUN git clone https://github.com/a1qatraineeship/docker_task.git ./webapps/task
EXPOSE 8083
CMD ["catalina.sh", "run"]